# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/vivado/CPU/CPU.cache/wt [current_project]
set_property parent.project_path D:/vivado/CPU/CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/vivado/CPU/CPU.srcs/sources_1/new/selecterFor5bits.v
  D:/vivado/CPU/CPU.srcs/sources_1/new/selecterFor32bits.v
  D:/vivado/CPU/CPU.srcs/sources_1/new/RegFile.v
  D:/vivado/CPU/CPU.srcs/sources_1/new/RAM.v
  D:/vivado/CPU/CPU.srcs/sources_1/new/PCSelecter.v
  D:/vivado/CPU/CPU.srcs/sources_1/new/PC.v
  D:/vivado/CPU/CPU.srcs/sources_1/new/instructionMemory.v
  D:/vivado/CPU/CPU.srcs/sources_1/new/decodeInstruction.v
  D:/vivado/CPU/CPU.srcs/sources_1/new/controlUnit.v
  D:/vivado/CPU/CPU.srcs/sources_1/new/aignZeroExtend.v
  D:/vivado/CPU/CPU.srcs/sources_1/new/ALU32.v
  D:/vivado/CPU/CPU.srcs/sources_1/new/CPU.v
}
synth_design -top CPUTOP -part xc7a35tcpg236-1
write_checkpoint -noxdef CPUTOP.dcp
catch { report_utilization -file CPUTOP_utilization_synth.rpt -pb CPUTOP_utilization_synth.pb }
